version: "3.9"

services:
  bd_postgres:
    image: postgres-mx:14.9                     #Ajuste version cambio en alloy
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: demo
      POSTGRES_USER: demo
      POSTGRES_DB: persona
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=es_MX.utf8 --lc-ctype=es_MX.utf8'
      # POSTGRES_INITDB_ARGS: '--encoding=UTF-8' # --lc-collate=C --lc-ctype=C'
      TZ: America/Mexico_City
    ports:
      - 5432:5432
volumes:
  postgresql_data: {}


# POSTGRES_PASSWORD to Postgres. Without specifying this, Postgres can’t run effectively. But there are also other variables that influence container behavior:
# POSTGRES_USER – Specifies a user with superuser privileges and a database with the same name. Postgres uses the default user when this is empty.
# POSTGRES_DB – Specifies a name for your database or defaults to the POSTGRES_USER value when left blank.
# POSTGRES_INITDB_ARGS – Sends arguments to postgres_initdb and adds functionality
# POSTGRES_INITDB_WALDIR – Defines a specific directory for the Postgres transaction log. A transaction is an operation and usually describes a change to your database.
# POSTGRES_HOST_AUTH_METHOD – Controls the auth-method for host connections to all databases, users, and addresses
# PGDATA – Defines another default location or subdirectory for database files
# These variables live within your plain text .env file. Ultimately, they determine how Postgres creates and