version: "3.9"

services:
  base_mysql:
    image: mysql:5.7.34
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      TZ: America/Mexico_City
    ports:
        - 3306:3306
volumes:
  db_data: {}
